/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.my.levirs.responsi.ui;

import id.my.levirs.responsi.controller.ProductController;
import id.my.levirs.responsi.data.model.Product;

import javax.swing.*;
import javax.swing.table.TableModel;

/**
 * @author levir
 */
public class ProductFrame extends javax.swing.JFrame implements ProductView {
    private ProductController mController;

    /**
     * Creates new form ProductFrame
     */
    public ProductFrame() {
        initComponents();
        mController = new ProductController(this);
    }

    @Override
    public void setTableModel(TableModel model) {
        mTable.setModel(model);
    }

    @Override
    public void updateSelected(Product product) {
        if (product == null) {
            mTable.clearSelection();
            mNamaField.setText("");
            mJumlahUnitField.setText("");
            mJamKerjaField.setText("");
            mJumlahTenagaKerjaField.setText("");
            mBiayaBahanBakuField.setText("");
            return;
        }

        mNamaField.setText(product.getNama());
        mJumlahUnitField.setText(String.valueOf(product.getJumlahUnit()));
        mJamKerjaField.setText(String.valueOf(product.getJamKerja()));
        mJumlahTenagaKerjaField.setText(String.valueOf(product.getJumlahTenagaKerja()));
        mBiayaBahanBakuField.setText(String.valueOf(product.getBiayaBahanBaku()));
    }

    @Override
    public void showMessage(String message, boolean isError) {
        JOptionPane.showMessageDialog(
                this,
                message,
                isError ? "Error" : "Pesan",
                isError ? JOptionPane.ERROR_MESSAGE : JOptionPane.PLAIN_MESSAGE
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25));
        jPanel1 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mNamaField = new javax.swing.JTextField();
        mJumlahUnitField = new javax.swing.JTextField();
        mJamKerjaField = new javax.swing.JTextField();
        mJumlahTenagaKerjaField = new javax.swing.JTextField();
        mBiayaBahanBakuField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        mCreateButton = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        mEditButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        mDeleteButton = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        mTable = new javax.swing.JTable();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        filler1.setAlignmentX(0.0F);
        getContentPane().add(filler1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pabrik Bela Negara");
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 16));
        getContentPane().add(jLabel1);

        filler2.setAlignmentX(0.0F);
        getContentPane().add(filler2);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));
        jPanel1.add(filler5);

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(216, 0));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 135));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {20, 125};
        jPanel3.setLayout(jPanel3Layout);

        jLabel2.setText("Nama Produk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Jumlah Unit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Jam Kerja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Jumlah Tenaga Kerja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Biaya Bahan Baku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        mNamaField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel3.add(mNamaField, gridBagConstraints);

        mJumlahUnitField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel3.add(mJumlahUnitField, gridBagConstraints);

        mJamKerjaField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel3.add(mJamKerjaField, gridBagConstraints);

        mJumlahTenagaKerjaField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel3.add(mJumlahTenagaKerjaField, gridBagConstraints);

        mBiayaBahanBakuField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        jPanel3.add(mBiayaBahanBakuField, gridBagConstraints);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        mCreateButton.setText("Create");
        mCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateButtonActionPerformed(evt);
            }
        });
        jPanel4.add(mCreateButton);
        jPanel4.add(filler9);

        mEditButton.setText("Edit");
        mEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditButtonActionPerformed(evt);
            }
        });
        jPanel4.add(mEditButton);
        jPanel4.add(filler8);

        mDeleteButton.setText("Delete");
        mDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteButtonActionPerformed(evt);
            }
        });
        jPanel4.add(mDeleteButton);
        jPanel4.add(filler7);

        jPanel2.add(jPanel4);
        jPanel2.add(filler6);

        jPanel1.add(jPanel2);
        jPanel1.add(filler3);

        mTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mTable);

        jPanel1.add(jScrollPane1);
        jPanel1.add(filler4);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCreateButtonActionPerformed
        mController.add(
                mNamaField.getText(),
                mJumlahUnitField.getText(),
                mJamKerjaField.getText(),
                mJumlahTenagaKerjaField.getText(),
                mBiayaBahanBakuField.getText()
        );
    }//GEN-LAST:event_mCreateButtonActionPerformed

    private void mEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditButtonActionPerformed
        mController.update(
                mNamaField.getText(),
                mJumlahUnitField.getText(),
                mJamKerjaField.getText(),
                mJumlahTenagaKerjaField.getText(),
                mBiayaBahanBakuField.getText()
        );
    }//GEN-LAST:event_mEditButtonActionPerformed

    private void mDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteButtonActionPerformed
        mController.delete();
    }//GEN-LAST:event_mDeleteButtonActionPerformed

    private void mTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mTableMouseClicked
        mController.setSelection(mTable.getSelectedRow());
    }//GEN-LAST:event_mTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mBiayaBahanBakuField;
    private javax.swing.JButton mCreateButton;
    private javax.swing.JButton mDeleteButton;
    private javax.swing.JButton mEditButton;
    private javax.swing.JTextField mJamKerjaField;
    private javax.swing.JTextField mJumlahTenagaKerjaField;
    private javax.swing.JTextField mJumlahUnitField;
    private javax.swing.JTextField mNamaField;
    private javax.swing.JTable mTable;
    // End of variables declaration//GEN-END:variables
}
